name: fluttcloud_flutter
description: A new Flutter project with Serverpod.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: 3.35.7

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Servberpod dependencies
  serverpod_flutter: 2.9.1
  serverpod_auth_email_flutter: 2.9.1
  serverpod_auth_shared_flutter: 2.9.1
  fluttcloud_client:
    path: ../fluttcloud_client
  #

  # Other dependencies
  flutter_native_splash: ^2.4.7
  package_info_plus: ^9.0.0
  auto_route: ^10.2.0
  logger: ^2.6.2
  injectable: ^2.5.2
  get_it: ^8.2.0
  watch_it: ^1.7.0
  easy_localization: ^3.0.8
  nb_utils: ^7.1.8
  collection: ^1.19.1
  universal_io: ^2.2.2
  toastification: ^3.0.3
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  shared_preferences: ^2.5.3
  path: ^1.9.1
  dio: ^5.9.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  file_picker: ^10.3.6
  chewie: ^1.13.0
  video_player: ^2.10.0
  fvp: ^0.35.0
  flutter_avif: ^3.1.0
  infinite_scroll_pagination: ^4.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.7.1
  analyzer: ^7.7.1
  auto_route_generator: ^10.2.5
  flutter_launcher_icons: ^0.14.4
  envied_generator: ^1.3.1
  injectable_generator: ^2.8.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  test: ^1.26.2
  flutter_gen_runner: ^5.12.0
  very_good_analysis: ^10.0.0
  inno_bundle: ^0.11.2

flutter:
  uses-material-design: true
  assets:
    - assets/localization/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true

inno_bundle:
  id: a326a4b0-58e1-11f0-a862-dbeb970b3c46
  publisher: asion
  name: FluttCloud
  admin: false
  languages:
    - english
